-- Core (bronze) tables as Delta. Translated from sql/ddl/02_core_tables.sql.
--   IDENTITY(1,1)              -> GENERATED BY DEFAULT AS IDENTITY, so the backfill from
--                                 Redshift can insert the source ids and new rows still
--                                 get generated ids. Identity columns must be BIGINT, so
--                                 customer_id widens from INTEGER to BIGINT everywhere.
--   CHAR(n)                    -> STRING (no blank padding, compare with trim())
--   GETDATE()                  -> current_timestamp()
--   DISTSTYLE/DISTKEY          -> dropped (no distribution in Delta)
--   SORTKEY                    -> CLUSTER BY (liquid clustering) on the former sort key
--   INTEGER/SMALLINT           -> INT/SMALLINT (unchanged)

CREATE TABLE IF NOT EXISTS migration_demo.core.customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_code STRING        NOT NULL,
    full_name     STRING        NOT NULL,
    email         STRING,
    region        STRING        NOT NULL COMMENT 'e.g. WEST, EAST',
    signup_date   DATE          NOT NULL,
    is_active     BOOLEAN       DEFAULT TRUE,
    created_at    TIMESTAMP     DEFAULT current_timestamp(),
    CONSTRAINT customers_pk PRIMARY KEY (customer_id)
)
USING DELTA
CLUSTER BY (signup_date)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

CREATE TABLE IF NOT EXISTS migration_demo.core.orders (
    order_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_id   BIGINT        NOT NULL,
    order_ts      TIMESTAMP     NOT NULL,
    order_status  STRING        NOT NULL COMMENT 'PLACED, SHIPPED, CANCELLED, ...',
    order_total   DECIMAL(12,2) NOT NULL,
    sales_channel STRING        DEFAULT 'web',
    loaded_at     TIMESTAMP     DEFAULT current_timestamp(),
    CONSTRAINT orders_pk PRIMARY KEY (order_id),
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
        REFERENCES migration_demo.core.customers (customer_id)
)
USING DELTA
CLUSTER BY (order_ts, customer_id)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

CREATE TABLE IF NOT EXISTS migration_demo.core.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    order_id      BIGINT        NOT NULL,
    sku           STRING        NOT NULL,
    quantity      SMALLINT      NOT NULL,
    unit_price    DECIMAL(10,2) NOT NULL,
    discount_pct  DECIMAL(5,4)  DEFAULT 0,
    CONSTRAINT order_items_pk PRIMARY KEY (order_item_id),
    CONSTRAINT order_items_order_fk FOREIGN KEY (order_id)
        REFERENCES migration_demo.core.orders (order_id)
)
USING DELTA
CLUSTER BY (order_id)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
